# KiBot output for generating Gerber files
# https://kibot.readthedocs.io/en/latest/configuration/outputs/excellon.html

kibot:
  version: 1

outputs:
- name: @NAME@
  comment: '@COMMENT@'
  type: excellon
  category: '@DIR@'
  dir: '@DIR@'
  options:
    generate_drill_files: @GENERATE_DRILL@
    pth_and_npth_single_file: @PTH_NPTH@
    pth_id: '@PTH_ID@'
    npth_id: '@NPTH_ID@'
    map: '@MAP_FORMAT@'

...
definitions:
  NAME: drl_pth_npth
  COMMENT: Drill in Excellon format
  DIR: Manufacturing/Fabrication/Gerbers
  GENERATE_DRILL: true
  PTH_NPTH: false
  PTH_ID: PTH
  NPTH_ID: NPTH
  MAP_FORMAT: None