name: CI

on:
  push:
    tags:
      - '*.*'
    branches:
      - master
      - dev

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'  # Ensures this job only runs on tag pushes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: Extract release notes
        uses: ffurrer2/extract-release-notes@v2
        id: extract-release-notes
        with:
          prerelease: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --notes '${{ steps.extract-release-notes.outputs.release_notes }}'
      
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v2
        with:
          tag: ${{ github.ref_name }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

  generate_tables:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate testpoints
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: testpoints
          skip: all
          variant: RELEASED
          config: kibot_yaml/kibot_main.yaml

      - name: Commit updated Tables
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update Testpoints

  generate_outputs:
    runs-on: ubuntu-latest
    needs: generate_tables
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get build info
        id: build_info
        run: |
          echo "Extract build date (verbose)"
          build_date=$(date +"%d-%b-%Y")
          echo "build_date=$build_date" >> $GITHUB_ENV

          echo "Extract build date (numeric)"
          build_date_num=$(date +"%Y-%m-%d")
          echo "build_date_num=$build_date_num" >> $GITHUB_ENV

      - name: Create definition file for version/date
        uses: "DamianReeves/write-file-action@master"
        with:
          path: kibot_yaml/kibot_version_date.yaml
          write-mode: overwrite
          contents: |
            # ##########################################################################
            # ### This file is generated by Build and Continuous Integration script  ###
            # ###   .github/workflows/ci.yaml                                        ###
            # ### Changes will be overwritten on the next workflow run               ###
            # ##########################################################################
            definition:
              build_date: "${{ steps.build_info.outputs.build_date }}"
              build_date_num: "${{ steps.build_info.outputs.build_date_num }}"
# build_version: "${{ steps.build_info.outputs.build_version }}"
          # echo "Extract latest tag as build version"
          # build_version=$(git describe --tags --abbrev=0)
          # echo "build_version=$build_version" >> $GITHUB_ENV
          # echo "::set-output name=build_version::$build_version"
          # echo "::set-output name=build_date::$build_date"
      - name: Verify Saved Build info
        run: |
          cat kibot_yaml/kibot_version_date.yaml

      - name: Cache 3D models data
        id: models-cache
        uses: set-soft/cache@main
        with:
          path: ~/cache_3d
          key: cache_3d

      - name: Generate outputs
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          # additional_args: -i testpoints
          additional_args: pdf_schematic
          variant: RELEASED
          config: kibot_yaml/kibot_main.yaml
          cache3D: YES

      - name: Commit updated Outputs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update Outputs