name: CI

on:
  push:
    tags:
      - '*.*'
    branches:
      - master
      - dev
    paths-ignore:
      - '*.md'

env:
  kibot_config: kibot_yaml/kibot_main.yaml

  # Used variant. We assume:
  # DRAFT: only schematic in progress, will only generate schematic PDF and BoM
  # PRELIMINARY: will generate both schematic and PCB documents, but no ERC/DRC
  # CHECKED: will generate both schematic and PCB documents, with ERC/DRC
  # RELEASED: similar to CHECKED, automatically selected when pushing a tag to master

  kibot_variant: CHECKED  

permissions:
  contents: write

jobs:
  release:
    needs: generate_outputs
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'  # Ensures this job only runs on tag pushes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git fetch
          git pull origin master
          
      - name: Extract release notes
        uses: ffurrer2/extract-release-notes@v2
        id: extract-release-notes
        with:
          prerelease: true

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     body: ${{ steps.extract-release-notes.outputs.release_notes }}
      #     draft: false
      #     prerelease: false
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ${{ steps.extract-release-notes.outputs.release_notes }}
          name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          files: |
            Schematic/*.pdf
            Manufacturing/*
            3D/*
            Testing/Testpoints/*.csv

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v2
        with:
          tag: ${{ github.ref_name }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
          push_options: '--force'

  generate_outputs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache 3D models data
        id: models-cache
        uses: set-soft/cache@main
        with:
          path: ~/cache_3d
          key: cache_3d

      - name: Determine VERSION Argument and Additional Args
        id: determine-version-and-args
        run: |
          last_tag=$(git describe --tags --abbrev=0 || echo "")
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            version_arg="-E REVISION='${last_tag}'"
            variant="RELEASED"
          else
            version_arg="-E REVISION='${last_tag}+ (Unreleased)'"
            variant="${{ env.kibot_variant }}"
          fi

          # Determine additional_args based on the variant
          case "$variant" in
            "DRAFT")
              additional_args="--skip-pre draw_fancy_stackup,erc,drc,include_table ${version_arg} draft_group"
              ;;
            "PRELIMINARY")
              additional_args="--skip-pre erc,drc ${version_arg} -i testpoints xlsx_bom"
              ;;
            "CHECKED"|"RELEASED")
              additional_args="${version_arg} -i testpoints xlsx_bom"
              ;;
            *)
              echo "Unknown variant: $variant"
              exit 1
              ;;
          esac

          echo "version_arg=${version_arg}" >> $GITHUB_ENV
          echo "additional_args=${additional_args}" >> $GITHUB_ENV
          echo "variant=${variant}" >> $GITHUB_ENV

      - name: Generate testpoints (Skipped for PRELIMINARY variant)
        if: ${{ env.kibot_variant != 'PRELIMINARY' }}
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: testpoints
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}

      - name: Generate outputs
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          additional_args: ${{ env.additional_args }}
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}
          cache3D: YES

      - name: Pull latest changes and push outputs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "Triggered by a tag, committing changes in detached HEAD state"
            git add -A
            git commit -m "Save changes before switching branches"

            DETACHED_COMMIT=$(git rev-parse HEAD)
            echo "Checking out the master branch"
            git fetch origin master
            git checkout master

            echo "Merging detached HEAD commit into master"
            git merge --no-ff $DETACHED_COMMIT -m "Merge outputs from tag-triggered workflow" -X theirs
          else
            echo "Triggered by a branch, using the current branch"
            git pull origin ${{ github.ref_name }} --tags --force
          fi

          # Make changes and commit
          git commit -a -m "Update Outputs" || echo "No changes to commit"

          # Push changes to the appropriate target
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "Pushing to master branch"
            git push origin master
          else
            echo "Pushing to ${{ github.ref_name }}"
            git push origin ${{ github.ref_name }}
          fi
