name: CI

on:
  push:
    tags:
      - '*.*'
    branches:
      - master
      - dev
    paths-ignore:
      - '*.md'

env:
  kibot_config: kibot_yaml/kibot_main.yaml
  kibot_variant: RELEASED

permissions:
  contents: write

jobs:
  release:
    needs: generate_outputs
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'  # Ensures this job only runs on tag pushes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: Extract release notes
        uses: ffurrer2/extract-release-notes@v2
        id: extract-release-notes
        with:
          prerelease: true

      # - name: Create release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: gh release create ${{ github.ref_name }} --notes '${{ steps.extract-release-notes.outputs.release_notes }}'
      
      # - name: Update changelog
      #   uses: thomaseizinger/keep-a-changelog-new-release@v2
      #   with:
      #     tag: ${{ github.ref_name }}

      # - name: Pull latest changes
      #   run: |
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "GitHub Actions"
      #     git fetch
      #     git pull origin master

      # - name: Commit updated CHANGELOG
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     branch: master
      #     commit_message: Update CHANGELOG
      #     file_pattern: CHANGELOG.md
          # push_options: '--force'

  # generate_tables:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Generate testpoints
  #       uses: INTI-CMNB/KiBot@v2_dk8
  #       with:
  #         targets: testpoints
  #         skip: all
  #         variant: RELEASED
  #         config: kibot_yaml/kibot_main.yaml

  #     - name: Pull latest changes
  #       run: |
  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"
  #         git config --global user.name "GitHub Actions"
  #         git pull --tags -f origin ${{ github.ref_name }}

  #     - name: Commit updated Tables
  #       uses: stefanzweifel/git-auto-commit-action@v5
  #       with:
  #         branch: ${{ github.ref }}
  #         commit_message: Update Testpoints

  generate_outputs:
    runs-on: ubuntu-latest
    # needs: generate_tables
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache 3D models data
        id: models-cache
        uses: set-soft/cache@main
        with:
          path: ~/cache_3d
          key: cache_3d

      - name: Generate testpoints
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: testpoints
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}

      - name: Generate outputs
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          # additional_args: -i testpoints
          additional_args: pdf_schematic
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}
          cache3D: YES

      - name: Pull latest changes and push outputs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
        # git commit -a -m "Update Outputs"
        # git push origin ${{ github.ref_name }}
      # git fetch
      # git pull --tags -f origin ${{ github.ref_name }}
      # git add .
      # git commit -m "Update Outputs"
      # git push origin ${{ github.ref_name }}

      - name: Commit updated Outputs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update Outputs
          # push_options: '--force'