name: CI

on:
  push:
    tags:
      - '*.*'
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'

env:
  kibot_config: kibot_yaml/kibot_main.yaml
  kibot_variant: RELEASED

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'  # Ensures this job only runs on tag pushes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: Extract release notes
        uses: ffurrer2/extract-release-notes@v2
        id: extract-release-notes
        with:
          prerelease: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --notes '${{ steps.extract-release-notes.outputs.release_notes }}'
      
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v2
        with:
          tag: ${{ github.ref_name }}

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

  out_testpoints:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate testpoints and check ERC/DRC
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: testpoints
          # skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit Updated Testpoints
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update Testpoints

  out_3d_render_top:
    runs-on: ubuntu-latest
    needs: out_testpoints
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache 3D models data
        id: models-cache
        uses: set-soft/cache@main
        with:
          path: ~/cache_3d
          key: cache_3d

      - name: Generate 3D renders PNG (Top)
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: png_3d_viewer_top
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}
          cache3D: YES

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit Updated 3D renders
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update 3D renders

  out_3d_render_bottom:
    runs-on: ubuntu-latest
    needs: out_testpoints
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache 3D models data
        id: models-cache
        uses: set-soft/cache@main
        with:
          path: ~/cache_3d
          key: cache_3d

      - name: Generate 3D renders PNG (Bottom)
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: png_3d_viewer_bottom
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}
          cache3D: YES

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit Updated 3D renders
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update 3D renders

  out_3d_render_angled_top:
    runs-on: ubuntu-latest
    needs: out_testpoints
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache 3D models data
        id: models-cache
        uses: set-soft/cache@main
        with:
          path: ~/cache_3d
          key: cache_3d

      - name: Generate 3D renders PNG (Angled Top)
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: png_3d_viewer_angled_top
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}
          cache3D: YES

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit Updated 3D renders
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update 3D renders

  out_3d_render_angled_bottom:
    runs-on: ubuntu-latest
    needs: out_testpoints
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache 3D models data
        id: models-cache
        uses: set-soft/cache@main
        with:
          path: ~/cache_3d
          key: cache_3d

      - name: Generate 3D renders PNG (Angled Bottom)
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: png_3d_viewer_angled_bottom
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}
          cache3D: YES

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit Updated 3D renders
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update 3D renders

  out_schematic:
    runs-on: ubuntu-latest
    needs: [out_3d_render_angled_top, out_3d_render_angled_bottom]
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Schematic PDF
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: pdf_schematic
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit Updated PDF Schematic
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update PDF Schematic

  out_netlist:
    runs-on: ubuntu-latest
    needs: out_testpoints
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Netlist
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: netlist
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit Updated Netlist
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update Netlist

  out_fab:
    runs-on: ubuntu-latest
    needs: out_testpoints
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Fabrication Document PDF
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: fab
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit Updated PDF Fabrication Document
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update PDF Fabrication Document

  out_pdf_assembly:
    runs-on: ubuntu-latest
    needs: [out_3d_render_top, out_3d_render_bottom, out_3d_render_angled_top, out_3d_render_angled_bottom]
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Assembly Document PDF
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: pdf_assembly
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit Updated PDF Assembly Document
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update PDF Assembly Document

  out_bom:
    runs-on: ubuntu-latest
    needs: out_testpoints
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate BoM files
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: bom
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit BoM files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update BoM files

  out_3d:
    runs-on: ubuntu-latest
    needs: out_testpoints
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate STEP file
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: 3d
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}

      - name: Commit Updated STEP file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update STEP file

  out_pos:
    runs-on: ubuntu-latest
    needs: out_testpoints
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Position file CSV
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          targets: csv_position
          skip: all
          variant: ${{ env.kibot_variant }}
          config: ${{ env.kibot_config }}   

      - name: Commit Updated Testpoints
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: Update Testpoints
  
  # generate_testpoints:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Generate testpoints
  #       uses: INTI-CMNB/KiBot@v2_dk8
  #       with:
  #         targets: testpoints
  #         skip: all
  #         variant: RELEASED
  #         config: kibot_yaml/kibot_main.yaml

  # generate_outputs:
  #   runs-on: ubuntu-latest
  #   needs: generate_testpoints
  #   steps:

  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Generate outputs
  #       uses: INTI-CMNB/KiBot@v2_dk8
  #       with:
  #         additional_args: -i testpoints
  #         variant: RELEASED
  #         config: kibot_yaml/kibot_main.yaml

  #     - name: Commit updated Outputs
  #       uses: stefanzweifel/git-auto-commit-action@v5
  #       with:
  #         branch: ${{ github.ref }}
  #         commit_message: Update Outputs